### ISSUE TITLE
Expose entire wordpress php directory as volume instead of just wp-uploads

### ISSUE THREAD

**Issue by pirate** [milanboers/wordpress-sqlite#1]
I'd like to migrate an existing wordpress setup to this image, but I want to be able to continue using my plugins and other customizations.

Is there any way to specify an entire wordpress php dir instead of just the wp-uploads dir?

Thanks! Excited to get this running, I've been dreaming of a wordpress+nginx+sqlite solution for a long time.

(Moved from this earlier issue on the wrong repo: https://github.com/milanboers/wordpress-nginx/issues/1).

**Comment by milanboers** [comment]
I guess you could mount the entire wp-content directory instead of just the uploads dir. What I personally do though, is add my plugins to the Dockerfile (just like the sqlite integration plugin now). This way you keep all static data inside the container image.

**Comment by pirate** [comment]
I think I'll just mount the whole thing, thanks!
