### ISSUE TITLE
your compose solution is actually working?

### ISSUE THREAD

**Issue by sunshine69** [milanboers/wordpress-sqlite#3]
Hi there,

I tried your docker-compose and see several things

- it might not work as it is because your nginx only filter ext .php and pass to the php fpm container however serving wordpress static files like css, js nginx has no clue. Thus my installation wizard display in browser is strange (no style at all)
- I need to fix the wordpress permissions by execting into teh ct and run

```
chown -R www-data:www-data /var/www 
find /var/www/ -type d -exec chmod 0755 {} ; 
find /var/www/ -type f -exec chmod 644 {} ;
```

Not sure if this is using podman-compose is the problems but I dont think the first issues is due to that as it wont be a different if run on docker or podman.

I dont know how to fix that cleanly yet, might be mounting the first container volume into the nginx in full (rather than only the upload folder)

**Comment by milanboers** [comment]
Hi,

I think the `volumes_from` line should be mounting the static files also into the nginx container. Only .php files are passed to the wordpress container, this is correct. Static files are supposed to be served directly from the nginx container. Perhaps something changed in later versions of the wordpress container which breaks it.

However I would not recommend using these projects anymore. The sqlite integration plugin has not been updated in 6 years and is closed. I myself also switched to a MariaDB.

**Comment by sunshine69** [comment]
Hi,

It is just for a small site so might be ok with sqlite3 however I will take your advice and see if security wise the plugin is good enough.

For your docker-compose the volume_from is fine however it requires files of the whole /var/www/html, and the volume form wont cover that. Mine one look like this and it works nicely

```cat docker-compose.yaml 
version: '2'
services:
    wp:
        image: milanb/wordpress-sqlite
        environment:
          - WP_HOME=https://store.kaykraft.org
          - WP_SITEURL=https://store.kaykraft.org
        volumes:
            - db:/var/www/db
            - uploads:/var/www/html/wp-content/uploads
            - webroot:/var/www/html
        restart: always
    http:
        image: milanb/wordpress-nginx
        links:
            - wp:wordpress
        volumes_from:
          - wp
        volumes:
          - ./ssl:/etc/nginx/ssl
          - ./conf.d:/etc/nginx/conf.d
        ports:
            - "443:443"
        restart: always
volumes:
    db:
        external: false
    uploads:
        external: false
    webroot:
        external: false
```
